branch-defaults:
  arjun:
    environment: node-express-env
    group_suffix: null
global:
  application_name: cis-550-project
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
